import Navbar from "@/components/layout/Navbar";
import Drawer from "@/components/layout/Drawer";
import "./globals.css";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="">
        <Drawer>
        <div className="flex flex-col h-screen justify-between">

          <header>
          <Navbar></Navbar>

          </header>
          <main className="mb-auto p-2">
          {children}
          </main>
          <Footer></Footer>
          </div>
        </Drawer>
      </body>
    </html>
  );
}
